---
- name: Playbook for setting up K8s nodes (masters and workers)
  hosts: all
  become: true
  vars:
    k8s_version: 1.26.0-00
    k8s_required_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    k8s_packages:
      - kubeadm={{ k8s_version }}
      - kubelet={{ k8s_version }}
      - kubectl={{ k8s_version }}
  tasks:
    - name: Installing required packages
      apt:
        name: "{{ k8s_required_packages }}"
        state: present
        update_cache: yes

    - name: Setting up containerd required modules
      copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/containerd.conf

    - name: Applying modprobe
      shell: modprobe overlay && modprobe br_netfilter

    - name: Setting up systcl conf
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        dest: /etc/sysctl.d/99-kubernetes-cri.conf

    - name: Restarting systcl
      command: sysctl --system

    - name: Create keyrings folder if not exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755
        recurse: yes

    - name: Installing containerd.io
      block:
        - name: Adding docker gpg key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name: Adding docker apt repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
            state: present
            filename: docker

        - name: Installing only containerd.io package
          apt:
            name: containerd.io
            state: present
            update_cache: yes

        # https://forum.linuxfoundation.org/discussion/862825/kubeadm-init-error-cri-v1-runtime-api-is-not-implemented
        - name: Removing default containerd.io config folder
          file:
            path: /etc/containerd/config.toml
            state: absent

        - name: Starting containerd service
          service:
            name: containerd
            state: started
            enabled: yes

    - name: Disabling swapp before process K8s installation
      block:
        - name: Remove all swap lines in /etc/fstab
          mount:
            name: "{{ item }}"
            fstype: swap
            state: absent
          loop:
            - swap
            - none

        - name: Disabling all swap
          command: swapoff -a
          when: ansible_swaptotal_mb > 0

    - name: Installing K8s packages
      block:
        - name: Adding K8s gpg key using url
          apt_key:
            url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version[0:3] }}/deb/Release.key
            state: present

        - name: Adding kubernetes apt repository
          apt_repository:
            repo: deb https://pkgs.k8s.io/core:/stable:/v{{ k8s_version[0:3] }}/deb/ /
            state: present
            filename: kubernetes

        - name: Installing K8s packages
          apt:
            name: "{{ k8s_packages }}"
            state: present
            update_cache: yes
          notify: Restart containerd

        - name: Starting kubelet service
          service:
            name: kubelet
            state: started
            enabled: yes

  # HANDLERS 
  # Restart Kubelet 
  handlers:
    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted
        enabled: yes
  # Restart containerd
    - name: Restart containerd
      service:
        name: containerd
        state: restarted
        enabled: yes

