IMAGE_NAME = "ubuntu/focal64"
PROVISION_FOLDER = "../provisioning"
NETWORK = "192.168.50."
MASTERS = Array.new
WORKERS = Array.new
WORKER_COUNT = 2

# Function to write to a file with given path and content
def write_to_file(filename, content)
    File.write(filename, content, mode: "w")
end

Vagrant.configure("2") do |config|
    config.vm.define "k8s-control-1" do |master|
        node_info = Hash[node_name: "k8s-control-1", node_ip: NETWORK + "10"]
        master.vm.box = IMAGE_NAME
        master.vm.hostname = node_info[:node_name]
        master.vm.network "private_network", ip: node_info[:node_ip]
        master.ssh.forward_agent = true
        master.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
        end
        # Append node info
        MASTERS.push(node_info)
    end

    (1..WORKER_COUNT).each do |node_id|
        config.vm.define "k8s-node-#{node_id}" do |node|
            node_info = Hash[node_name: "k8s-node-#{node_id}", node_ip: NETWORK + "#{20 + node_id}"]
            node.vm.box = IMAGE_NAME
            node.vm.hostname = node_info[:node_name]
            node.vm.network "private_network", ip: node_info[:node_ip]
            node.ssh.forward_agent = true
            node.vm.provider "virtualbox" do |vb_node|
                vb_node.memory = 1024
                vb_node.cpus = 1
            end
            # Append node info
            WORKERS.push(node_info)
        end
    end

    config.vm.define "controller" do |machine|
        # Create inventory file for vagrant
        inventory_path = "#{PROVISION_FOLDER}/only_for_vagrant/inventory"
        content = "controller ansible_connection=local\n"
        # Merge MASTERS and WORKERS arrays
        nodes = MASTERS.concat(WORKERS)
        nodes.each do |item|
            content += "#{item[:node_name]} ansible_host=#{item[:node_ip]} "
            content += "ansible_ssh_private_key_file=/home/vagrant/host_keys/#{item[:node_name]}/virtualbox/private_key\n"
        end
        write_to_file(inventory_path, content)
        # VM controller setup
        machine.vm.network "private_network", ip: NETWORK + "11"
        machine.vm.box = IMAGE_NAME
        machine.vm.hostname = "controller"
        machine.ssh.forward_agent = true
        machine.vm.provider "virtualbox" do |vb_ctrl|
            vb_ctrl.memory = 1024
            vb_ctrl.cpus = 1
        end
        #===================
        #|   Provisions    |
        #===================
        user_home_dir = "/home/vagrant"
        # Copying hosts private key in order to change permissions
        machine.vm.provision "file", source: ".vagrant/machines", destination:"#{user_home_dir}/host_keys"
        # Changing hosts private key permissions for ssh
        machine.vm.provision "shell", inline: "chmod 0600 #{user_home_dir}/host_keys/*/virtualbox/private_key"
        machine.vm.provision "file", source: "#{PROVISION_FOLDER}", destination: "#{user_home_dir}/.ansible"
        # Masters provision
        machine.vm.provision :ansible_local do |ansible|
          ansible.provisioning_path  = "#{user_home_dir}/.ansible/only_for_vagrant"
          ansible.playbook       = "../playbooks/k8s-master-setup.yml"
          ansible.verbose        = true
          ansible.install        = true
          ansible.limit          = "k8s-control-*"
          ansible.inventory_path = "inventory"
          ansible.extra_vars     = {
            local_user: "vagrant",
            apiserver_address: MASTERS[0][:node_ip]
          }
        end
        # Workers provision
        machine.vm.provision :ansible_local do |ansible|
            ansible.provisioning_path  = "#{user_home_dir}/.ansible/only_for_vagrant"
            ansible.playbook       = "../playbooks/k8s-worker-setup.yml"
            ansible.verbose        = true
            ansible.install        = true
            ansible.limit          = "k8s-node-*"
            ansible.inventory_path = "inventory"
            ansible.extra_vars     = {
                local_user: "vagrant"
          }
          end
    end
end 