#!/bin/bash

echo "Setting up AZURE login credentials..."
export ARM_CLIENT_ID=""
export ARM_CLIENT_SECRET=""
export ARM_TENANT_ID=""
export ARM_SUBSCRIPTION_ID=""
echo "Setting up AZURE login credentials finish !"